version: '3'
services:
  mongo:
    image: mongo
    container_name: wekamongo
    restart: always
  wekarest:
    image: chloec/log8371-tp2:weka
    container_name: wekarest
    restart: always
    links:
      - "mongo:mongodb"
    ports:
      - "8081:8080"
    depends_on:
      - mongo
    labels:
      - "service-name:weka"
      - "service-type:app-srv"
      - "environment:test"
